#' Mega-tree of Plants based on Open Tree of Life
#'
#' This tree was based on Brown and Smith (2018), which in turn was based on the Open Tree of Life.
#' It was copied from `V.PhyloMaker::GBOTB.extended`. After then, node labels were added for empty ones.
#'
#' @format A phylogeny with class "phylo". It is also a list. Compare with a normal phylo object, it has another data frame `tree_plant_otl$genus_family_root`, which provides the root nodes information for every unique genus and family in the phylogeny. Such information can be used to insert new tips onto the phylogeny later.
#' @source https://github.com/jinyizju/V.PhyloMaker/tree/master/data
#' @references Smith, S. A., & Brown, J. W. (2018). Constructing a broadly inclusive seed plant phylogeny. American Journal of Botany, 105(3), 302-314.
#'
#' Jin, Y., & Qian, H. (2019). V. PhyloMaker: an R package that can generate very large phylogenies for vascular plants. Ecography.
"tree_plant_otl"

#' Mega-tree of 11638 Fish from The Fish Tree of Life
#'
#' This tree was generated by Rabosky et al. (2018). It has 11638 tips that all have sequence data. Node labels were added here.
#'
#' @format A phylogeny with class "phylo". It is also a list. Compare with a normal phylo object, it has another data frame `tree_fish_12k$genus_family_root`, which provides the root nodes information for every unique genus and family in the phylogeny. Such information can be used to insert new tips onto the phylogeny later.
#' @source https://fishtreeoflife.org/downloads/actinopt_12k_treePL.tre.xz
#' @references Rabosky, D. L., Chang, J., Title, P. O., Cowman, P. F., Sallan, L., Friedman, M., ... & Alfaro, M. E. (2018). An inverse latitudinal gradient in speciation rate for marine fishes. Nature, 559(7714), 392.
#' @seealso tree_fish_32k_n100
#'
"tree_fish_12k"

#' 100 Mega-tree of 31516 Fish from The Fish Tree of Life
#'
#' This tree was generated by Rabosky et al. (2018). It has 31516 tips, with species missing sequence data added using birth-death models. Therefore, there are 100 such posterior distribution phylogenies to account for uncertainty. The authors suggested not to use them to conduct trait evolution analyses.
#'
#' @format A phylogeny with class "multiPhylo". It is also a list. Each phylogeny also has another data frame `genus_family_root`, which provides the root nodes information for every unique genus and family in the phylogeny. Such information can be used to insert new tips onto the phylogeny later.
#' @source https://fishtreeoflife.org/downloads/actinopt_full.trees.xz
#' @references Rabosky, D. L., Chang, J., Title, P. O., Cowman, P. F., Sallan, L., Friedman, M., ... & Alfaro, M. E. (2018). An inverse latitudinal gradient in speciation rate for marine fishes. Nature, 559(7714), 392.
#' @seealso tree_fish_12k
#'
"tree_fish_32k_n100"


#' 100 randomly selected Mega-tree of Birds from Bird Tree.
#'
#' The first 50 phylogenies are randomly selected from those 10000 trees with Ericson backbond generated by Jetz et al. (2012); and the second 50 phylogenies are randomly selected from those 10000 trees with Hackett backbone. Node labels were added for each phylogeny.
#'
#' @format A phylogeny with class "multiPhylo". It is also a list. Compare with a normal phylo object, each phylogeny has another data frame `genus_family_root`, which provides the root nodes information for every unique genus and family in the phylogeny. Such information can be used to insert new tips onto the phylogeny later.
#' @source https://data.vertlife.org/
#' @references Jetz, W., Thomas, G. H., Joy, J. B., Hartmann, K., & Mooers, A. O. (2012). The global diversity of birds in space and time. Nature, 491(7424), 444.
#'
"tree_bird_n100"

#' 100 randomly selected Mega-tree of Mammals from PHYLACINE V1.2.
#'
#' These 100 phylogenies are randomly selected from the 1000 trees generated by Faurby et al. (2018). Node labels were added here.
#'
#' @format A phylogeny with class "multiPhylo". It is also a list. Compare with a normal phylo object, each phylogeny has another data frame `genus_family_root`, which provides the root nodes information for every unique genus and family in the phylogeny. Such information can be used to insert new tips onto the phylogeny later.
#' @source https://github.com/MegaPast2Future/PHYLACINE_1.2/blob/master/Data/Phylogenies/Complete_phylogeny.nex
#' @references Faurby, S., Davis, M., Pedersen, R. Ø., Schowanek, S. D., Antonelli, A., & Svenning, J. C. (2018). PHYLACINE 1.2: The phylogenetic atlas of mammal macroecology. Ecology, 99(11), 2626-2626.
#' @seealso tree_mammal_n100_vertlife
#'
"tree_mammal_n100_phylacine"


#' 100 randomly selected Mega-tree of Mammals from VertLife.
#'
#' The first 50 phylogenies are randomly selected from those 10000 trees with Node Dating Exponential backbone provided by Upham et al. (2019); and the second 50 phylogenies are randomly selected from those 10000 trees with Fossil Birth Death Zhou et al.'s backbone. Node labels were added for each phylogeny.
#'
#' @format A phylogeny with class "multiPhylo". It is also a list. Compare with a normal phylo object, each phylogeny has another data frame `genus_family_root`, which provides the root nodes information for every unique genus and family in the phylogeny. Such information can be used to insert new tips onto the phylogeny later.
#' @source https://vertlife.org/data/mammals/
#' @references Upham, N. S., Esselstyn, J. A., & Jetz, W. (2019). Inferring the mammal tree: species-level sets of phylogenies for questions in ecology, evolution, and conservation. PLoS biology, 17(12), e3000494.
#'
"tree_mammal_n100_vertlife"

#' 100 randomly selected Mega-tree of Amphibians from VertLife.
#'
#' @format A phylogeny with class "multiPhylo". It is also a list, with the first to be the "consensus" tree (the other 99 are posterior phylogenies). Compare with a normal phylo object, each phylogeny has another data frame `genus_family_root`, which provides the root nodes information for every unique genus and family in the phylogeny. Such information can be used to insert new tips onto the phylogeny later.
#' @source http://vertlife.org/data/amphibians/
#' @references Jetz, W., & Pyron, R. A. (2018). The interplay of past diversification and evolutionary isolation with present imperilment across the amphibian tree of life. Nature ecology & evolution, 2(5), 850-858.
#'
"tree_amphibian_n100"

#' 100 randomly selected Mega-tree of Reptiles (Squamates) from VertLife.
#'
#' @format A phylogeny with class "multiPhylo". It is also a list. Compare with a normal phylo object, each phylogeny has another data frame `genus_family_root`, which provides the root nodes information for every unique genus and family in the phylogeny. Such information can be used to insert new tips onto the phylogeny later.
#' @source https://vertlife.org/data/squamates/
#' @references Tonini, J. F. R., Beard, K. H., Ferreira, R. B., Jetz, W., & Pyron, R. A. (2016). Fully-sampled phylogenies of squamates reveal evolutionary patterns in threat status. Biological Conservation, 204, 23-31.
#'
"tree_reptile_n100"


#' 100 randomly selected Mega-tree of Sharks, Rays, and Chimaeras from VertLife.
#'
#' @format A phylogeny with class "multiPhylo". It is also a list. Compare with a normal phylo object, each phylogeny has another data frame `genus_family_root`, which provides the root nodes information for every unique genus and family in the phylogeny. Such information can be used to insert new tips onto the phylogeny later.
#' @source https://vertlife.org/data/sharks//
#' @references Stein, R. W., Mull, C. G., Kuhn, T. S., Aschliman, N. C., Davidson, L. N., Joy, J. B., ... & Mooers, A. O. (2018). Global priorities for conserving the evolutionary history of sharks, rays and chimaeras. Nature ecology & evolution, 2(2), 288-298.
#'
"tree_shark_ray_n100"


