#' Mega-tree of Plants based on Open Tree of Life
#'
#' This tree was based on Smith and Brown (2018), which in turn was based on the Open Tree of Life.
#' It was copied from `V.PhyloMaker::GBOTB.extended`. After then, node labels were added for empty ones.
#'
#' @format A phylogeny with class "phylo". It is also a list. Compare with a normal phylo object, it has another data frame `tree_plant_otl$genus_family_root`, which provides the root nodes information for every unique genus and family in the phylogeny. Such information can be used to insert new tips onto the phylogeny later.
#' @source https://github.com/jinyizju/V.PhyloMaker/tree/master/data
#' @references Smith, S. A., & Brown, J. W. (2018). Constructing a broadly inclusive seed plant phylogeny. American Journal of Botany, 105(3), 302-314.
#'
#' Jin, Y., & Qian, H. (2019). V. PhyloMaker: an R package that can generate very large phylogenies for vascular plants. Ecography.
"tree_plant_otl"


#' Mega-tree of Plants based on Carruthers et al., 2026
#'
#' This tree was based on Carruthers et al. (2026), which in turn was an update of the Smith and Brown (2018).
#'
#' @format A phylogeny with class "phylo". It is also a list. Compare with a normal phylo object, it has another data frame `tree_plant_Carruthers$genus_family_root`, which provides the root nodes information for every unique genus and family in the phylogeny. Such information can be used to insert new tips onto the phylogeny later.
#' @source https://www.biorxiv.org/content/10.64898/2026.01.06.695000v1
#' @references Carruthers et al., (2026). A large phylogenetic tree for euphyllophytes. bioRxiv.
#'
"tree_plant_Carruthers"

#' Mega-tree of 11638 Fish from The Fish Tree of Life
#'
#' This tree was generated by Rabosky et al. (2018). It has 11638 tips that all have sequence data. Node labels were added here.
#'
#' @format A phylogeny with class "phylo". It is also a list. Compare with a normal phylo object, it has another data frame `tree_fish_12k$genus_family_root`, which provides the root nodes information for every unique genus and family in the phylogeny. Such information can be used to insert new tips onto the phylogeny later.
#' @source https://fishtreeoflife.org/downloads/actinopt_12k_treePL.tre.xz
#' @references Rabosky, D. L., Chang, J., Title, P. O., Cowman, P. F., Sallan, L., Friedman, M., ... & Alfaro, M. E. (2018). An inverse latitudinal gradient in speciation rate for marine fishes. Nature, 559(7714), 392.
#' @seealso tree_fish_32k_n50
#'
"tree_fish_12k"



#' The summary tree by McTavish et al. 2025 PNAS
#'
#' This is the [summary tree v1.6 by McTavish et al. 2025](https://github.com/McTavishLab/AvesData/blob/main/Tree_versions/Aves_1.6/Clements2025/summary_dated_clements.nex). It used the taxonomy of eBird (Clements 2025).
#'
#' @format A phylogeny with class 'phylo'. Compare with a normal phylo object, each phylogeny has another data frame `genus_family_root`, which provides the root nodes information for every unique genus and family in the phylogeny. Such information can be used to insert new tips onto the phylogeny later.
#' @source https://github.com/McTavishLab/AvesData/blob/main/Tree_versions/Aves_1.6/Clements2025/summary_dated_clements.nex
#' @references E.J. McTavish,J.A. Gerbracht,M.T. Holder,M.J. Iliff,D. Lepage,P.C. Rasmussen,B.D. Redelings,L.L. Sánchez Reyes,& E.T. Miller,  A complete and dynamic tree of birds, Proc. Natl. Acad. Sci. U.S.A. 122 (18) e2409658122, https://doi.org/10.1073/pnas.2409658122 (2025).
"tree_bird_McTavish"


#' The Maximum Likely Mega-tree of Bees from Bee Tree of Life
#'
#' @format A maximum likely phylogeny with class "phylo". Compare with a normal phylo object, this phylogeny has another data frame `genus_family_root`, which provides the root nodes information for every unique genus and family in the phylogeny. Such information can be used to insert new tips onto the phylogeny later.
#' @source http://beetreeoflife.org
#' @references Henríquez-Piskulich, P.; Hugall, A.F.; Stuart-Fox; D. 2023. A supermatrix phylogeny of the world’s bees (Hymenoptera: Anthophila). bioRxiv 2023.06.16.545281. doi.org/10.1101/2023.06.16.545281.
#'
"tree_bee"


#' Tree of 2244 butterfly species
#'
#' This tree was generated by Kawahara et al. (2023).
#'
#' @format A phylogeny with class "phylo". It is also a list. Compare with a normal phylo object, it has another data frame `tree_butterfly$genus_family_root`, which provides the root nodes information for every unique genus and family in the phylogeny. Such information can be used to insert new tips onto the phylogeny later.
#' @source https://springernature.figshare.com/articles/dataset/A_global_phylogeny_of_butterflies_reveals_their_evolutionary_history_ancestral_host_plants_and_biogeographic_origins/21774899?file=39124943
#' @references Kawahara, Akito Y., et al. "A global phylogeny of butterflies reveals their evolutionary history, ancestral hosts and biogeographic origins." Nature ecology & evolution 7.6 (2023): 903-913.
"tree_butterfly"
